import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import FlyonuiScript from "@/components/FlyonuiScript";
import Navbar2 from "@/components/Navbar2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatWith AI",
  icons: {
    icon: "/icons/favicon.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Navbar2 />
      {children}
      <FlyonuiScript />
    </div>
  );
}
